-- Cập nhật đáp án chuẩn 100% cho 60 câu hỏi kỳ thi CA4 Văn bằng 2 CAND
UPDATE exam_questions_mc SET correct_answer = 'D' WHERE order_index = 1;
UPDATE exam_questions_mc SET correct_answer = 'A' WHERE order_index = 2;
UPDATE exam_questions_mc SET correct_answer = 'B' WHERE order_index = 3;
UPDATE exam_questions_mc SET correct_answer = 'B' WHERE order_index = 4;
UPDATE exam_questions_mc SET correct_answer = 'B' WHERE order_index = 5;
UPDATE exam_questions_mc SET correct_answer = 'C' WHERE order_index = 6;
UPDATE exam_questions_mc SET correct_answer = 'C' WHERE order_index = 7;
UPDATE exam_questions_mc SET correct_answer = 'D' WHERE order_index = 8;
UPDATE exam_questions_mc SET correct_answer = 'D' WHERE order_index = 9;
UPDATE exam_questions_mc SET correct_answer = 'B' WHERE order_index = 10;
UPDATE exam_questions_mc SET correct_answer = 'A' WHERE order_index = 11;
UPDATE exam_questions_mc SET correct_answer = 'A' WHERE order_index = 12;
UPDATE exam_questions_mc SET correct_answer = 'B' WHERE order_index = 13;
UPDATE exam_questions_mc SET correct_answer = 'A' WHERE order_index = 14;
UPDATE exam_questions_mc SET correct_answer = 'A' WHERE order_index = 15;
UPDATE exam_questions_mc SET correct_answer = 'B' WHERE order_index = 16;
UPDATE exam_questions_mc SET correct_answer = 'D' WHERE order_index = 17;
UPDATE exam_questions_mc SET correct_answer = 'B' WHERE order_index = 18;
UPDATE exam_questions_mc SET correct_answer = 'C' WHERE order_index = 19;
UPDATE exam_questions_mc SET correct_answer = 'C' WHERE order_index = 20;
UPDATE exam_questions_mc SET correct_answer = 'B' WHERE order_index = 21;
UPDATE exam_questions_mc SET correct_answer = 'B' WHERE order_index = 22;
UPDATE exam_questions_mc SET correct_answer = 'A' WHERE order_index = 23;
UPDATE exam_questions_mc SET correct_answer = 'A' WHERE order_index = 24;
UPDATE exam_questions_mc SET correct_answer = 'D' WHERE order_index = 25;
UPDATE exam_questions_mc SET correct_answer = 'C' WHERE order_index = 26;
UPDATE exam_questions_mc SET correct_answer = 'D' WHERE order_index = 27;
UPDATE exam_questions_mc SET correct_answer = 'D' WHERE order_index = 28;
UPDATE exam_questions_mc SET correct_answer = 'C' WHERE order_index = 29;
UPDATE exam_questions_mc SET correct_answer = 'A' WHERE order_index = 30;
UPDATE exam_questions_mc SET correct_answer = 'B' WHERE order_index = 31;
UPDATE exam_questions_mc SET correct_answer = 'B' WHERE order_index = 32;
UPDATE exam_questions_mc SET correct_answer = 'D' WHERE order_index = 33;
UPDATE exam_questions_mc SET correct_answer = 'D' WHERE order_index = 34;
UPDATE exam_questions_mc SET correct_answer = 'C' WHERE order_index = 35;
UPDATE exam_questions_mc SET correct_answer = 'B' WHERE order_index = 36;
UPDATE exam_questions_mc SET correct_answer = 'C' WHERE order_index = 37;
UPDATE exam_questions_mc SET correct_answer = 'D' WHERE order_index = 38;
UPDATE exam_questions_mc SET correct_answer = 'B' WHERE order_index = 39;
UPDATE exam_questions_mc SET correct_answer = 'C' WHERE order_index = 40;
UPDATE exam_questions_mc SET correct_answer = 'B' WHERE order_index = 41;
UPDATE exam_questions_mc SET correct_answer = 'C' WHERE order_index = 42;
UPDATE exam_questions_mc SET correct_answer = 'A' WHERE order_index = 43;
UPDATE exam_questions_mc SET correct_answer = 'B' WHERE order_index = 44;
UPDATE exam_questions_mc SET correct_answer = 'C' WHERE order_index = 45;
UPDATE exam_questions_mc SET correct_answer = 'B' WHERE order_index = 46;
UPDATE exam_questions_mc SET correct_answer = 'B' WHERE order_index = 47;
UPDATE exam_questions_mc SET correct_answer = 'B' WHERE order_index = 48;
UPDATE exam_questions_mc SET correct_answer = 'C' WHERE order_index = 49;
UPDATE exam_questions_mc SET correct_answer = 'B' WHERE order_index = 50;
UPDATE exam_questions_mc SET correct_answer = 'C' WHERE order_index = 51;
UPDATE exam_questions_mc SET correct_answer = 'C' WHERE order_index = 52;
UPDATE exam_questions_mc SET correct_answer = 'D' WHERE order_index = 53;
UPDATE exam_questions_mc SET correct_answer = 'C' WHERE order_index = 54;
UPDATE exam_questions_mc SET correct_answer = 'Nhà nước đơn nhất' WHERE order_index = 55;
UPDATE exam_questions_mc SET correct_answer = 'Tập trung dân chủ' WHERE order_index = 56;
UPDATE exam_questions_mc SET correct_answer = '4' WHERE order_index = 57;
UPDATE exam_questions_mc SET correct_answer = 'Năng lực pháp luật' WHERE order_index = 58;
UPDATE exam_questions_mc SET correct_answer = 'Vô ý do cẩu thả' WHERE order_index = 59;
UPDATE exam_questions_mc SET correct_answer = 'Trách nhiệm kỷ luật' WHERE order_index = 60;
